import { formatter } from "@lingui/format-po";
import type { LinguiConfig } from "@lingui/conf";

/**
 * Lingui i18n configuration for the Kandev web SPA.
 *
 * - English (`en`) is the source locale; its catalog is generated by extraction.
 * - `pseudo` is a generated pseudo-locale used for QA: it accents/pads every
 *   message so an un-transformed (plain-English) string on screen reveals a
 *   literal that was never externalized. Never hand-edit the pseudo catalog.
 *
 * Catalogs are committed as `.po`; the Vite plugin (`@lingui/vite-plugin`)
 * compiles `.po` imports on the fly, and `pnpm compile` produces standalone
 * output for CI checks.
 */
const config: LinguiConfig = {
  sourceLocale: "en",
  locales: ["en", "pseudo"],
  pseudoLocale: "pseudo",
  catalogs: [
    {
      path: "<rootDir>/src/locales/{locale}/messages",
      include: [
        "<rootDir>/app",
        "<rootDir>/components",
        "<rootDir>/lib",
        "<rootDir>/src",
        "<rootDir>/hooks",
      ],
      exclude: ["**/node_modules/**", "**/*.test.ts", "**/*.test.tsx", "**/e2e/**", "**/dist/**"],
    },
  ],
  format: formatter({ origins: true, lineNumbers: false }),
};

export default config;
